// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn0R6DqeivwKsEJOhCIEwW4zU4S3y8H6A',
    appId: '1:1081751679173:web:d10b04e64caf90363680ac',
    messagingSenderId: '1081751679173',
    projectId: 'tarotai-4cc0b',
    authDomain: 'tarotai-4cc0b.firebaseapp.com',
    storageBucket: 'tarotai-4cc0b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDde0W8sQ3Mm27-khHOrZ82IitzGXRyjb4',
    appId: '1:1081751679173:android:1468044665788d3c3680ac',
    messagingSenderId: '1081751679173',
    projectId: 'tarotai-4cc0b',
    storageBucket: 'tarotai-4cc0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwlz6nZn0czYZjdFEFv82L2v3OE38OtCU',
    appId: '1:1081751679173:ios:58b2b5748695b36a3680ac',
    messagingSenderId: '1081751679173',
    projectId: 'tarotai-4cc0b',
    storageBucket: 'tarotai-4cc0b.firebasestorage.app',
    iosBundleId: 'com.example.tarotAi1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwlz6nZn0czYZjdFEFv82L2v3OE38OtCU',
    appId: '1:1081751679173:ios:58b2b5748695b36a3680ac',
    messagingSenderId: '1081751679173',
    projectId: 'tarotai-4cc0b',
    storageBucket: 'tarotai-4cc0b.firebasestorage.app',
    iosBundleId: 'com.example.tarotAi1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn0R6DqeivwKsEJOhCIEwW4zU4S3y8H6A',
    appId: '1:1081751679173:web:339ab1b2148035de3680ac',
    messagingSenderId: '1081751679173',
    projectId: 'tarotai-4cc0b',
    authDomain: 'tarotai-4cc0b.firebaseapp.com',
    storageBucket: 'tarotai-4cc0b.firebasestorage.app',
  );
}
